package com.chihuo.bussiness;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

// Generated 2012-10-5 16:47:30 by Hibernate Tools 3.4.0.CR1

/**
 * Desk generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Desk implements java.io.Serializable {
	@XmlElement
	private int id;
	@XmlElement
	private String name;
	@XmlElement
	private Integer capacity;
	
	@XmlTransient
	private Integer status;

	@XmlTransient
	private Restaurant restaurant;
	
	@XmlTransient
	private DeskType deskType;
	
	public Desk() {
	}

	public Desk(int id) {
		this.id = id;
	}

	public Desk(int id, DeskType deskType, String name, Integer capacity) {
		this.id = id;
		this.deskType = deskType;
		this.name = name;
		this.capacity = capacity;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public DeskType getDeskType() {
		return this.deskType;
	}

	public void setDeskType(DeskType deskType) {
		this.deskType = deskType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Restaurant getRestaurant() {
		return restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

}
