package com.chihuo.bussiness;

// Generated 2012-10-5 16:47:30 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DeskType generated by hbm2java
 */
public class DeskType implements java.io.Serializable {

	private Integer id;
	private Restaurant restaurant;
	private String name;
	private Set<Desk> desks = new HashSet<Desk>(0);

	public DeskType() {
	}

	public DeskType(Restaurant restaurant, String name, Set<Desk> desks) {
		this.restaurant = restaurant;
		this.name = name;
		this.desks = desks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Desk> getDesks() {
		return this.desks;
	}

	public void setDesks(Set<Desk> desks) {
		this.desks = desks;
	}

}
