package com.chihuo.bussiness;

// Generated 2012-10-5 16:47:30 by Hibernate Tools 3.4.0.CR1

/**
 * Desk generated by hbm2java
 */
public class Desk implements java.io.Serializable {

	private int id;
	private DeskType deskType;
	private String name;
	private Integer capacity;

	public Desk() {
	}

	public Desk(int id) {
		this.id = id;
	}

	public Desk(int id, DeskType deskType, String name, Integer capacity) {
		this.id = id;
		this.deskType = deskType;
		this.name = name;
		this.capacity = capacity;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public DeskType getDeskType() {
		return this.deskType;
	}

	public void setDeskType(DeskType deskType) {
		this.deskType = deskType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

}
