package com.chihuo.bussiness;

// Generated 2012-12-2 14:48:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer id;
	private String name;

	public Role() {
	}

	public Role(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
